modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/TeamLapen/Werewolves/issues"
license = "LGPL-3.0"

[[mods]]
modId = "werewolves"
namespace = "werewolves"
version = "${version}"
displayName = "Werewolves"
updateJSONURL = "http://myurl.me/"
displayURL = "https://vampirism.maxanier.de"
logoFile = "logo.png"
credits = "RebelT (models/textures)"
authors = "Cheaterpaul"
[[dependencies.werewolves]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.werewolves]]
modId = "teamlapenlib"
mandatory = true
versionRange = "[${vampirism_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.werewolves]]
modId = "vampirism"
mandatory = true
versionRange = "[${vampirism_version},)"
ordering = "AFTER"
side = "BOTH"