name: Publish Test

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Deploy Targets (for testing)'
        type: choice
        default: all
        required: true
        options:
          - curseforge
          - maven
          - all

permissions:
  contents: read

jobs:
  publish-test:
    environment: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Publish All
        if: ${{ github.event.inputs.target == 'all' }}
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build publish curseforge -PMAVEN_URL=${{ secrets.MAVEN_URL }} -PMAVEN_USER=${{ secrets.MAVEN_USER }} -PMAVEN_TOKEN=${{ secrets.MAVEN_TOKEN }} -PCURSEFORGE_API=${{ secrets.CURSEFORGE_API }} -PCROWDIN_KEY=${{ secrets.CROWDIN_KEY }} -Ptesting
      - name: Publish Curseforge
        if: ${{ github.event.inputs.target == 'curseforge' }}
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build curseforge -PCURSEFORGE_API=${{ secrets.CURSEFORGE_API }} -PCROWDIN_KEY=${{ secrets.CROWDIN_KEY }} -Ptesting
      - name: Publish Maven
        if: ${{ github.event.inputs.target == 'maven' }}
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build publish -PMAVEN_URL=${{ secrets.MAVEN_URL }} -PMAVEN_USER=${{ secrets.MAVEN_USER }} -PMAVEN_TOKEN=${{ secrets.MAVEN_TOKEN }} -PCROWDIN_KEY=${{ secrets.CROWDIN_KEY }} -Ptesting
